### PR TITLE
Magic pen

### LINKED ISSUE #54: New text copy tool to work with books, posters, signs etc.
Allow reading text content from any node that displays text or contains text.
Allow writing to nodes that can be written without special tools.

- [x] basic_signs (r/w)
- [x] books (r/w)
- [x] display_modpack https://github.com/pyrollo/display_modpack (r/w)
- [x] default signs (r/w)
- [x] digiterms https://github.com/pyrollo/digiterms (r)
- [x] digilines:lcd (r)
- [x] digistuff panel & touchscreen (r)
- [x] geocache (r)
- [x] lua controller
- [x] lua tube (r/w)
- [x] posters (r/w)
- [x] travelnet (r)
       broken: only copies target name, was supposed to copy all travelnet names in network.

Extras:
- [x] Write title and author to lua controller / lua tube code as comments.
- [x] Parse title from lua controller / lua tube comments. Use coords only if suitable comment line not found. Use results as tool infotext.

API:
- [x] Allow leaving copy or paste function undefined.
- [x] Ability to set max size for tool storage.
- [x] Ability to set custom wield texture (different from inventory icon) and scaling.

This should also implement #51 Should it be just read or read+write? Luatool has other special functions for memory debugging and cloning.
If it would be just read then Luatool should still implement reading from books even if not writing to books...

Use feather for recipe if feather is available :chicken: 

Note https://github.com/S-S-X/metatool/issues/51#issuecomment-714035115 should probably also go through limits and apply those to not allow storing more data than normally possible, probably should not add splitting or at least no automatic splitting as it can get confusing to use.
Message about partial write could be good if target node should not store as much as tool storage contains:
> the lua controller can store more data than a book can. I remember using books for backups and having to split it up into multiple books.

### PR DESCRIPTION
**Pull request by S-S-X**
Closes #54 

Requires some testing / bug hunting. There's bugs for sure simply because how it is hacked together through different kinds of application hacking interfaces, actually there's even few actual more or less useful programming interfaces.

All planned nodes not implemented yet but many signs and other nodes are, see list: #54 .
So far I've not checked if feather pen is okay, and maybe should change wield texture to something bit cleaner.
I think inventory texture is fine for both feather and graphite variants.

Also mod.conf is not compatible with https://github.com/minetest/contentdb/issues/243
Next release would be lua debugging tools anyway, not this one.
But when merging this add issue as reminder if ContentDB ticket is still open.

### CODE REVIEW

**Comment by S-S-X** [comment]
Pasting over 300k content (copied from book) to road_signs:
```
2020-11-07 18:45:37: ACTION[Server]: SX uses metatool:magic_pen, pointing at [node under=-175,10,21 above=-175,10,22]
2020-11-07 18:45:38: ERROR[Server]: In thread 7fd300f4b700:
2020-11-07 18:45:38: ERROR[Server]: /build/minetest-6u0nkv/minetest-5.3.0/src/script/cpp_api/s_base.cpp:8c: static int ScriptApiBase::luaPanic(lua_State*): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (not enough memory)
```
Maybe add some limits for tool memory, could maybe add this as tool definition option directly to API so it is easy to adjust and limits all content.

**Comment by 6r1d** [comment]
[World.mt](https://pastebin.com/FUamxFyU) for context

**Comment by 6r1d** [comment]
Transfer from `digistuff:panel` and `digilines:lcd` to `homedecor:book_blue` works.
I can't apply text to the displays, but I guess this is intended behavior.

**Comment by S-S-X** [comment]
@6r1d yes it is intended behavior, quote from issue #54 
> Allow reading text content from any node that displays text or contains text.
> Allow writing to nodes that can be written without special tools.

**Comment by 6r1d** [comment]
What about travelnets? I can copy station group and name, but I can't apply them to either new or working travelnet.
By the way, I'm using Sokomine's version of Travelnet, there might be forks that function differently.

**Comment by S-S-X** [comment]
> What about travelnets? I can copy station group and name, but I can't apply them to either new or working travelnet.
> By the way, I'm using Sokomine's version of Travelnet, there might be forks that function differently.

Travelnet copy function seems to be broken, it was actually intended to copy network name and full text list of travelnet names in that network.
Not sure if applying travelnet, owner and network to single travelnet is better than allowing to copy list of connected travelnet names without ability to apply any data for travelnets. Because applying data to another travelnet will not work if there is already travelnet with same name in network.

It could be used to move travelnets:
* Copy travelnet name, owner and network to tool memory.
* Remove travelnet and place it again to some different location.
* Apply copied data to new travelnet to easily place it back to original network and with same name.

Or it could be used to copy list of travelnets in network to books, posters, etc.
* Copy travelnet name, owner and network to tool memory.
* Apply copied data to poster or book

That is pick one situation, not sure which is more useful but probably travelnet data cloning is not really that important and therefore maybe should do read only (copy list of travelnets in network), allow writing only to books/posters/signs/etc. but not to travelnets.

So options would be either to fix copying list of travelnet names or implement applying copied travelnet data to actual travelnet boxes.

**Comment by S-S-X** [comment]
Added Lua controller / lua tube comment parsing and fixed travelnet network reading, no write support added for travelnets.
Only owner can copy travelnet targets with coordinates, anyone can copy targets without coordinates.

**Comment by SwissalpS** [comment]
> Not sure if applying travelnet, owner and network to single travelnet is better than allowing to copy list of connected travelnet names without ability to apply any data for travelnets. Because applying data to another travelnet will not work if there is already travelnet with same name in network.

I don't think it is required to apply to travelnet. Being able to copy to book is great. Mostly at least the name will change when I re-place travelnet.

**Pull request merged**
