### PR TITLE
add mooncontroller support

### PR DESCRIPTION
**Pull request by SwissalpS**
copies and pastes both code and memory from one mooncontroller to another

### CODE REVIEW

**Comment by SwissalpS** [comment]
I did try adding it to 'lua controller' group, but memory paste did not work.  
While luaC code runs fine in mooncontroller, the opposite is not always true, so I didn't bother to find a solution to make the tool work for both, although it would be cool when upgrading to mooncontroller to be able to use existing tools with luaC contents.

**Comment by BuckarooBanzay** [comment]
oh, i just saw this after i created my mooncontroller PR :confused: sorry ... #133

**Comment by S-S-X** [comment]
Noticed this only after merging #133
Could test that one a bit and if there's issues that can't be reliably solved within same group then override #133 with this.

**Comment by SwissalpS** [comment]
np, as long as we can use luatool one way or the other :D

**Comment by SwissalpS** [comment]
closing as #133 seems to be working.

**Pull request closed without merging**
